[package]
name = "derive-tree-sitter-macros"
version = "0.0.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
darling = "0.20"
proc-macro2 = "1"
syn = { version = "2", features = ["full"] }
quote = "1"
